variable "mode" {
  description = "Onboarding mode for Oracle Cloud compartments: one of \"all\", \"include\", or \"exclude\"."
  type        = string
  default     = "all"

  validation {
    condition     = contains(["all", "include", "exclude"], var.mode)
    error_message = "mode must be one of: all, include, exclude."
  }
}

variable "tenancy_ocid" {
  description = "OCID of the tenancy (root compartment)."
  type        = string
}

variable "policy_compartment_ocid" {
  description = "Compartment OCID where the generated policy will be created. Defaults to the tenancy."
  type        = string
  default     = ""
}

variable "policy_name" {
  description = "Name for the generated policy resource."
  type        = string
  default     = "codex-observability-policy"
}

variable "policy_description" {
  description = "Optional description for the generated policy."
  type        = string
  default     = "Automated access policy generated by the Codex onboarding module."
}

variable "principal_type" {
  description = "Type of the principal receiving access. Typically \"group\" or \"dynamic-group\"."
  type        = string
  default     = "group"

  validation {
    condition = (
      var.cross_tenancy_enabled ?
      contains(["group", "dynamic-group"], var.principal_type) :
      contains(["group", "dynamic-group", "user"], var.principal_type)
    )
    error_message = "principal_type must be group or dynamic-group when cross_tenancy_enabled is true; otherwise one of: group, dynamic-group, user."
  }
}

variable "principal_name" {
  description = "Name of the OCI principal (group, dynamic group, or user) receiving access."
  type        = string
}

variable "cross_tenancy_enabled" {
  description = "Enable cross-tenancy access using Define/Endorse/Admit policy statements."
  type        = bool
  default     = false
}

variable "principal_tenancy_ocid" {
  description = "Home tenancy OCID for the remote principal (required when cross_tenancy_enabled is true)."
  type        = string
  default     = ""

  validation {
    condition = (
      var.cross_tenancy_enabled ?
      length(trimspace(var.principal_tenancy_ocid)) > 0 :
      true
    )
    error_message = "principal_tenancy_ocid must be provided when cross_tenancy_enabled is true."
  }
}

variable "principal_tenancy_alias" {
  description = "Alias assigned to the remote tenancy in Define/Admit statements (required when cross_tenancy_enabled is true)."
  type        = string
  default     = ""

  validation {
    condition = (
      var.cross_tenancy_enabled ?
      length(trimspace(var.principal_tenancy_alias)) > 0 :
      true
    )
    error_message = "principal_tenancy_alias must be provided when cross_tenancy_enabled is true."
  }
}

variable "principal_group_ocid" {
  description = "OCID of the principal group in the remote tenancy (required when cross_tenancy_enabled is true and principal_type is group)."
  type        = string
  default     = ""

  validation {
    condition = (
      var.cross_tenancy_enabled && var.principal_type == "group" ?
      length(trimspace(var.principal_group_ocid)) > 0 :
      true
    )
    error_message = "principal_group_ocid must be provided when cross_tenancy_enabled is true and principal_type is group."
  }
}

variable "policy_permissions" {
  description = "Policy permissions applied to each compartment. Each entry defines the verb/action, target resource type, and optional where clause."
  type = list(object({
    action       = string
    resource     = string
    where_clause = optional(string, "")
  }))
  default = [
    {
      action       = "inspect"
      resource     = "all-resources"
      where_clause = ""
    },
    {
      action       = "read"
      resource     = "all-resources"
      where_clause = ""
    }
  ]
}

variable "additional_policy_statements" {
  description = "Additional raw policy statements to append to the generated list."
  type        = list(string)
  default     = []
}

variable "mode_debug" {
  description = "Set true to retain intermediate maps in the Terraform state for troubleshooting."
  type        = bool
  default     = false
}

# ==============================================================================
# ALL mode variables
# ==============================================================================

variable "all_excluded_compartment_ocids" {
  description = "ALL mode: compartment OCIDs to exclude from onboarding."
  type        = list(string)
  default     = []
}

# ==============================================================================
# INCLUDE mode variables
# ==============================================================================

variable "included_compartment_ocids" {
  description = "INCLUDE mode: compartments (and their subcompartments) to include."
  type        = list(string)
  default     = []
}

variable "included_leaf_compartment_ocids" {
  description = "INCLUDE mode: specific compartments to include, typically outside included_compartment_ocids subtrees."
  type        = list(string)
  default     = []
}

variable "include_excluded_compartment_ocids" {
  description = "INCLUDE mode: compartments to omit even if they fall under the included_compartment_ocids subtrees."
  type        = list(string)
  default     = []
}

# ==============================================================================
# EXCLUDE mode variables
# ==============================================================================

variable "excluded_compartment_ocids" {
  description = "EXCLUDE mode: compartment OCIDs whose entire subtrees should be excluded."
  type        = list(string)
  default     = []
}

variable "exclude_additional_compartment_ocids" {
  description = "EXCLUDE mode: additional compartment OCIDs to remove even if not under excluded_compartment_ocids."
  type        = list(string)
  default     = []
}

variable "exception_compartment_ocids" {
  description = "EXCLUDE mode: compartment OCIDs to force-include even if they fall within excluded subtrees."
  type        = list(string)
  default     = []
}

# ==============================================================================
# Legacy/Additional configuration
# ==============================================================================

variable "extra_compartment_ocids" {
  description = "Optional list of compartment OCIDs that should always receive the generated policies."
  type        = list(string)
  default     = []
}
